### ISSUE TITLE
DMRS transformations to RDF is broken

### ISSUE THREAD

**Issue by arademaker** [own-pt/delphin-rdf#19]
SENT: A person is riding the bicycle on one wheel

We have 3 analyses but each analysis should be a separate graph. But notes are being reused..  BTW,   `<http://ibm.com/sick-b/22/nodes#node10002#predicate>` is not a valid URI (no two `#`)

**Comment by yfaria** [comment]
I think the code behaviour when we have 3 analyses is not well described yet (our tests were made with the gold profile of ERG, so it wasn't in our tests). The profile is the same from #17, isn't it? What was the command that you used in the CLI?

**Comment by yfaria** [comment]
Checking the sick-b, the problem when there is more than 1 analysis for each sentence is that both have the same id in the profile; so the nodes end up with the same names. I can think of two major ways to solve this problem:

- create the notion of profile and make the transform depend on those profile specific things;
- just abandon the id in the profile and rename the URI with a unique number for each analysis, it can be a unique number associated with the id as well (v.g., if we have two analysis with the id `5104`, we could put `5104-01` and `5104-02`).

I believe that the first is more scalable, but will increase the RDF output in size (not much tough).

About the URIs with two `#`, the problem was solved in the [url-check](https://github.com/own-pt/delphin-rdf/tree/url_check). I'll PR when I solve the ids problem

**Comment by arademaker** [comment]
Can you please enumerate here all the URIs that we need to generate in the MRS-RDF and DRMS-RDF? So we can decide about the patterns we should use.

**Comment by arademaker** [comment]
For instance, if we take {prefix} to be an URI for the profile:

1. The DMRS: <{prefix}/item/{num}-{analysis}> 
2. A node <{prefix}/item/{num}-{analysis}/node/{number}>
3. An edge <{prefix}/item/{num}-{analysis}/edge/{number}> 

etc

**Comment by arademaker** [comment]
I believe we can close it now. This is about a bug now solved. Additional improvements being discussed in #21
